XRPLF/xrpl-py

xrpl/ledger/__init__.py
xrpl/ledger/main.py

This PR implements the following ledger feature:
- Get the most recent open ledger
Python SDK sugar
CI passes.

Implements ledger sugar methods

---

docs/source/xrpl.models.amounts.rst
docs/source/xrpl.models.currencies.rst
xrpl/models/requests/request.py

Things found in the process of double checking that everything public in the repo is documented.
Only fixes:
* Doesn't mark request `method` as a required field (since it's filled by the object). 
* Cleans up `xrpl.models.currency`
* Adds the new types `Amount` and `Currency
Python SDK cleanup.
CI passes.

Implements minor doc fixes

---

.readthedocs.yaml
CHANGELOG.md
README.md

Adds CHANGELOG, docs badge to README, and readthedocs config

adds changelog and docs badge to readme

---

xrpl/core/binarycodec/__init__.py
xrpl/core/binarycodec/main.py
xrpl/core/keypairs/__init__.py
xrpl/core/keypairs/crypto_implementation.py
xrpl/core/keypairs/ed25519.py
xrpl/core/keypairs/main.py
xrpl/core/keypairs/secp256k1.py

I tested generating the docs and rewrote the strings for the binarycodec and keypairs modules to be more internally consistent and easier to read.

Better doc strings for keypairs and binary codec.

---

CONTRIBUTING.md
README.md
docs/index.rst

Revise README

---

.github/pull_request_template.md
CODEOWNERS
tests/binarycodec/test_main.py
xrpl/core/binarycodec/types/serialized_dict.py

Adds codeowners and PR template.
Python SDK cleanup.
Will be seen with the next PR.

Fixes repo organization

---

docs/source/xrpl.models.currencies.rst
tests/addresscodec/test_codec.py
tests/binarycodec/test_main.py
tests/keypairs/test_main.py
tests/models/requests/test_sign.py
xrpl/__init__.py
xrpl/clients/exceptions.py
xrpl/core/__init__.py
xrpl/core/addresscodec/codec.py
xrpl/core/addresscodec/exceptions.py
xrpl/core/binarycodec/exceptions.py
xrpl/core/binarycodec/types/serialized_dict.py
xrpl/core/keypairs/exceptions.py
xrpl/core/keypairs/main.py
xrpl/models/__init__.py
xrpl/models/exceptions.py
xrpl/models/requests/channel_authorize.py
xrpl/models/requests/sign.py
xrpl/models/requests/sign_and_submit.py
xrpl/models/requests/sign_for.py
xrpl/transaction/exceptions.py
xrpl/wallet/main.py
xrpl/wallet/wallet_generation.py

Title says it all. Also resolved some errors in documentation generation.
Python SDK cleanup.
CI passes. Double-checked that the problem is solved by hand.

Exports modules at the top level

---

xrpl/transaction/main.py

Python SDK final touches
CI passes.

Implements separate non-autofill and autofill `sign` methods

---

README.md
tests/integration/requests/test_submit_multisigned.py
tests/integration/requests/test_submit_only.py
tests/integration/reusable_values.py
tests/integration/sugar/test_account.py
tests/integration/sugar/test_transaction.py
tests/integration/sugar/test_wallet.py
tests/integration/transactions/test_account_delete.py
tests/integration/transactions/test_account_set.py
tests/integration/transactions/test_check_cancel.py
tests/integration/transactions/test_check_cash.py
tests/integration/transactions/test_check_create.py
tests/integration/transactions/test_deposit_preauth.py
tests/integration/transactions/test_escrow_cancel.py
tests/integration/transactions/test_escrow_create.py
tests/integration/transactions/test_escrow_finish.py
tests/integration/transactions/test_offer_cancel.py
tests/integration/transactions/test_payment.py
tests/integration/transactions/test_payment_channel_claim.py
tests/integration/transactions/test_payment_channel_fund.py
tests/integration/transactions/test_set_regular_key.py
tests/integration/transactions/test_signer_list_set.py
tests/integration/transactions/test_trust_set.py
xrpl/wallet/main.py
xrpl/wallet/wallet_generation.py

Cleans up the wallet module

---

xrpl/models/transactions/__init__.py
xrpl/models/transactions/account_set.py
xrpl/models/transactions/offer_create.py

Python SDK release
Regenerated documentation, made sure it looked good

Adds transaction flag constants

---

.github/workflows/unit_test.yml

This PR makes the unit test CI run on PRs from forks rather than just from branches. It also allows us to run the unit test CI by hand in case stuff doesn't work for some reason in the future.
CI didn't run on #230 and #225
Will push and see if that fixes the issues

Fixes CI on PRs from forks

---

README.md

Did a once over on the README, and propose some legibility and aesthetic updates like using pycon blocks for repl stuff

update README for legibility, aesthetics

---

CHANGELOG.md
tests/unit/models/transactions/test_transaction.py
xrpl/models/transactions/transaction.py

Python library 1.1.0
Added simple test. CI passes.

Adds option for a Transaction's flags to be a List of ints

---

README.md
docs/source/xrpl.models.amounts.rst
docs/source/xrpl.models.currencies.rst
docs/source/xrpl.rst

This PR:
* Shows all the inherited members for amount/currency objects
* Fixes the use of `send_reliable_submission` in the README
* Fixes repeating content on the "XRP Global Variables" page
Python SDK bugfixes

Fixes minor docs errors

---

xrpl/__init__.py

Title says it all. Closes #222.
Python library bugfixes
CI passes.

Exports `xrpl.utils` at the top level

---

xrpl/account/__init__.py

Python library bugfixes
CI passes.

Exports `get_account_root` in `xrpl.account`

---

CHANGELOG.md
xrpl/models/transactions/__init__.py
xrpl/models/transactions/payment_channel_claim.py

Title says it all. Missed it when working on #219.
Python SDK v1.1.0
CI passes.

Adds PaymentChannelClaim flags

---

CHANGELOG.md
xrpl/transaction/__init__.py
xrpl/transaction/reliable_submission.py

This PR refactors the reliable submission method to be asynchronous, and adds a synchronous method that is wrapped around the async method.
Python library 1.1.0
CI passes.

Adds asynchronous reliable submission method

---

CHANGELOG.md

Title says it all. 
Python v1.1 release
N/A

Cleans up Changelog

---

xrpl/models/__init__.py

Title says it all. Makes it easier to import models.
v1.1
CI passes. I also checked the docs and made sure they didn't go wonky.

Exports all models at the top models level

---

tests/unit/core/binarycodec/types/test_path_set.py
tests/unit/models/currencies/test_issued_currency.py
xrpl/constants.py
xrpl/core/binarycodec/types/currency.py
xrpl/models/currencies/issued_currency.py

Improve fix from #266 based on learnings!

improve currency fix

---

CHANGELOG.md
tests/integration/reqs/test_no_ripple_check.py
xrpl/asyncio/clients/utils.py
xrpl/models/requests/request.py

Fixes an issue with sending `NoRippleCheck` requests

fixes no_ripple_check request

---

CHANGELOG.md
xrpl/asyncio/clients/async_client.py
xrpl/asyncio/clients/async_websocket_client.py
xrpl/asyncio/clients/client.py
xrpl/asyncio/clients/json_rpc_base.py
xrpl/asyncio/clients/websocket_base.py
xrpl/clients/sync_client.py
xrpl/clients/websocket_client.py
xrpl/core/binarycodec/types/hash.py
xrpl/core/binarycodec/types/serialized_type.py
xrpl/core/keypairs/crypto_implementation.py
xrpl/models/path.py

Improves docs on websocket clients and uses OO for common client initializes

update docs for clients

---

CODEOWNERS
pyproject.toml

This PR removes codeowners.
@ledhed2222 and I are no longer the owners of this repo
Code isn't touched.

chore: remove CODEOWNERS

---

CHANGELOG.md
tests/integration/transactions/test_ticket_create.py
xrpl/core/binarycodec/definitions/definitions.json
xrpl/models/transactions/__init__.py
xrpl/models/transactions/ticket_create.py
xrpl/models/transactions/types/transaction_type.py

Title says it all. 
[`TicketBatch` amendment](https://xrpscan.com/amendment/955DF3FA5891195A9DAEFA1DDC6BB244B545DDE1BAA84CBB25D5F12A8DA68A0C) is now enabled.
CI passes.

feat: Add `TicketCreate` transaction model

---

CHANGELOG.md
xrpl/asyncio/clients/websocket_base.py
xrpl/clients/websocket_client.py

Replaces runtime `assert`s with `typing.cast` to address https://github.com/XRPLF/xrpl-py/issues/270

replace runtime assert with cast

---

CHANGELOG.md
tests/unit/models/amounts/test_issued_currency_amount.py
tests/unit/models/currencies/test_issued_currency.py
tests/unit/models/currencies/test_xrp.py
xrpl/models/amounts/issued_currency_amount.py
xrpl/models/currencies/issued_currency.py
xrpl/models/currencies/xrp.py

These methods make it way easier to work with these objects.
CI passes. Added tests for the new features.

feat: methods to convert between IssuedCurrency and IssuedCurrencyAmount

---

CHANGELOG.md
tests/unit/utils/test_str_conversions.py
xrpl/utils/__init__.py
xrpl/utils/str_conversions.py

Adds `xrpl.utils.str_to_hex` and `xrpl.utils.hex_to_str` helper functions. This is necessary for NFT stuff, but also for some other fields that already exist in XRPL.

add hex_to_str and str_to_hex helpers

---

xrpl/asyncio/transaction/reliable_submission.py

This PR makes the error messages for reliable submission easier to understand. Right now, all errors are "latest ledger sequence > last ledger sequence".
This is a followup to #308. I noticed while dogfooding that the error messages are now really hard to understand and debug, because you don't get the preliminary result in the error messages.
This doesn't need a CHANGELOG update because it's incorporated in the line for #308.
CI passes. Tested the fix empirically.

fix: better error messages for reliable submissions

---

xrpl/constants.py
xrpl/core/binarycodec/types/account_id.py
xrpl/core/binarycodec/types/uint64.py
xrpl/utils/xrp_conversions.py

quick regular expression use cleanup

---

CHANGELOG.md
tests/integration/sugar/test_wallet.py
tests/unit/asyn/wallet/test_wallet_generation.py
xrpl/asyncio/wallet/wallet_generation.py
xrpl/wallet/wallet_generation.py

Add ability to specify a custom wallet host in `generate_faucet_wallet`

add custom faucet host param to generate_faucet_wallet

---

CHANGELOG.md
pyproject.toml

release 1.4.0

---

.github/dependabot.yml

Better dependency management
N/A

chore: set up dependabot

---

tests/unit/models/transactions/test_nftoken_create_offer.py
xrpl/models/transactions/nftoken_create_offer.py

rename nft sell offer flag

---

CHANGELOG.md
pyproject.toml

Update to 1.5.0

---

.github/workflows/integration_test.yml
.github/workflows/unit_test.yml
poetry.lock
pyproject.toml

This PR adds `coverage.py` as a dev dep and tests code coverage.
Testing out a package
CI passes. Threshold for code coverage is met.

chore: add code coverage testing

---

CHANGELOG.md
tests/integration/sugar/test_wallet.py
tests/unit/asyn/wallet/test_wallet_generation.py
xrpl/asyncio/wallet/wallet_generation.py

Add wallet inferencing option for amm devnet
Amm devnet is now public

feat: add amm devnet support for wallet inferencing

---

CHANGELOG.md
xrpl/asyncio/account/main.py
xrpl/asyncio/account/transaction_history.py
xrpl/asyncio/clients/async_client.py
xrpl/asyncio/clients/async_websocket_client.py
xrpl/asyncio/clients/client.py
xrpl/asyncio/clients/json_rpc_base.py
xrpl/asyncio/clients/websocket_base.py
xrpl/asyncio/ledger/main.py
xrpl/asyncio/transaction/ledger.py
xrpl/asyncio/transaction/main.py
xrpl/asyncio/transaction/reliable_submission.py
xrpl/clients/sync_client.py
xrpl/clients/websocket_client.py

Changed `request_impl` to `_request_impl`
It should not be used outside of the library - causes confusion

refactor: Make request_impl into a private function

---

.vscode/settings.json
docs/conf.py
tests/integration/integration_test_case.py
tests/integration/it_utils.py

mypy kept popping up with these errors.
Passes mypy locally (CI only checks the `xrpl` folder). CI passes.

fix: small typing errors in tests

---

CHANGELOG.md
xrpl/models/requests/account_objects.py

Test it out @ https://xrpl.org/websocket-api-tool.html#account_objects on the testnet:
```
{
"id": 1,
"command": "account_objects",
"account": "rKtJzUSnxWVi89EqRsWsLTVckEtNQDeS9S",
"ledger_index": "validated",
"type": "nft_offer",
"limit": 10
}
```

Add nft_offer type in AccountObjects

---

README.md

Add code snippets link to README and fix a typo

---

snippets/README.md

Add README to snippets folder to point to xrpl.org code samples.

---

tests/integration/sugar/test_wallet.py
tests/unit/asyn/wallet/test_wallet_generation.py
xrpl/asyncio/wallet/wallet_generation.py

fix: hooks v3 testnet

---

CHANGELOG.md
tests/integration/sugar/test_wallet.py
xrpl/asyncio/wallet/wallet_generation.py

The sidechain devnet is important for sidechain work. The faucet generation didn't support it previously.
CI passes.

feat: add sidechain devnet support to faucet generation

---

CHANGELOG.md
pyproject.toml

Changes to be released before 2.0.0
Release
CI passes

Release xrpl-py 1.9.0

---

CHANGELOG.md
README.md
tests/integration/sugar/test_account.py
tests/integration/sugar/test_transaction.py
tests/unit/core/addresscodec/test_main.py
tests/unit/core/binarycodec/types/test_amount.py

Several fixes required for the 2.0 branch discovered after the original feature PRs.
Separating this into a separate PR to preserve the history of main only having PR's as opposed to odd commits.
* Adds unit tests to pass test coverage CI
* Fixes a newly failing test

feat: 2.0 rebase fixes

---

CHANGELOG.md
pyproject.toml

Releasing xrpl-py 2.0.0
Updating CHANGELOG for version update.
CI Passes

release: version 2.0.0 

---

README.md

Updating the README to be easier to read + get started from. Also added a link to the migration guide in case it's helpful for discovering what to do.
When adding the migration guide I noticed the first example code snippet was hard to use, so replaced it with code from the `submit_a_payment.py` code snippet with a few comment updates.
CI Passes

docs: Update README with migration guide and more relevant tutorial

---

tests/integration/it_utils.py
tests/integration/reusable_values.py
tests/integration/sugar/test_account.py

The methods in `it_utils` have a special naming convention that needs to be followed in order for them to be used in integration tests.
CI passes.

fix(tests): allow fund_wallet to be used in integration tests

---

.github/workflows/integration_test.yml
CONTRIBUTING.md

Update docker file to xrpld:1.12.0-b1

---

pyproject.toml

release 2.1.0

---

CHANGELOG.md
pyproject.toml

Release xrpl-py 2.2.0

---

CHANGELOG.md
pyproject.toml

2.3 release

---

CHANGELOG.md
tests/unit/models/transactions/test_payment.py
tests/unit/models/transactions/test_transaction.py
xrpl/models/transactions/transaction.py
xrpl/utils/parse_nftoken_id.py

fix: better error handling if wallet is passed into account/destination

---

CHANGELOG.md
pyproject.toml

release: v2.4

---

CHANGELOG.md
tests/integration/sugar/test_wallet.py
tests/unit/asyn/wallet/test_wallet.py
xrpl/asyncio/wallet/wallet_generation.py

The AMM dev network will be decommissioned on 12/8

feat: remove AMM devnet

---

CHANGELOG.md
tests/unit/models/transactions/test_better_transaction_flags.py
xrpl/models/transactions/payment.py

Rectify the incorrect usage of the transaction flag from `TF_NO_DIRECT_RIPPLE` to `TF_NO_RIPPLE_DIRECT`
Updated the tests to use the new flag name

Rectify flag name TF_NO_RIPPLE_DIRECT

---

.vscode/extensions.json
.vscode/settings.json
CONTRIBUTING.md

- Add recommended extensions for VS code
- Remove deprecated vscode settings and add new ones
- Updated contributing.md to reference latest version of python

chore: Update vscode extensions & python-version

---

CHANGELOG.md
pyproject.toml

Release 2.6.0- update pyproject and CHANGELOG

---

CHANGELOG.md
xrpl/models/requests/__init__.py
xrpl/models/requests/nfts_by_issuer.py
xrpl/models/requests/request.py

Title
Following https://ripplelabs.atlassian.net/jira/software/projects/DEFI/boards/760?assignee=712020%3Aff4deb34-7fc1-428e-a2ee-354e1ddba309&selectedIssue=DEFI-128 & https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/clio-methods/nfts_by_issuer/

Add nfts_by_issuer data type

---

CHANGELOG.md
pyproject.toml

v3.0.0 release

---

CHANGELOG.md
pyproject.toml

4.1.0 release

---

CHANGELOG.md
tests/unit/asyn/wallet/test_main.py
xrpl/wallet/main.py

Revert "fix: Update default cryptographic algorithm in `Wallet` class methods"
