XRPLF/xrpl-py

xrpl/wallet/main.py

I disagree with flake8's opinion that there shouldn't be a blank line between the docstring to start `__init__()` and the doc comment describing `self.seed`.

Updated docstrings for wallet module

---

tests/binarycodec/test_main.py
xrpl/core/binarycodec/types/serialized_dict.py

Replaces #172 since that PR broke when the repo moved.

Binary codec: allow X-addresses alongside matching SourceTag/DestinationTag

---

docs/index.rst
docs/source/xrpl.utils.rst
tests/utils/test_time_conversions.py
tests/utils/test_xrp_conversions.py
xrpl/utils/__init__.py
xrpl/utils/time_conversions.py
xrpl/utils/xrp_conversions.py

Adds some conversion utilities for feature-parity with ripple-lib:
- Convert from decimal (`int`, `float`, or `decimal.Decimal`) XRP to drops of XRP and back (to Decimal)
- Convert from XRP Ledger's "Ripple Epoch" time format to Python-native time types and back.

Add conversion utilities

---

docs/source/xrpl.models.rst
docs/source/xrpl.models.transactions.rst
xrpl/models/base_model.py
xrpl/models/transactions/__init__.py
xrpl/models/transactions/account_delete.py
xrpl/models/transactions/account_set.py
xrpl/models/transactions/check_cancel.py
xrpl/models/transactions/check_cash.py
xrpl/models/transactions/check_create.py
xrpl/models/transactions/deposit_preauth.py
xrpl/models/transactions/escrow_cancel.py
xrpl/models/transactions/escrow_create.py
xrpl/models/transactions/escrow_finish.py
xrpl/models/transactions/offer_cancel.py
xrpl/models/transactions/offer_create.py
xrpl/models/transactions/payment.py
xrpl/models/transactions/payment_channel_claim.py
xrpl/models/transactions/payment_channel_create.py
xrpl/models/transactions/payment_channel_fund.py
xrpl/models/transactions/set_regular_key.py
xrpl/models/transactions/signer_list_set.py
xrpl/models/transactions/transaction.py

Improve Transaction model doc strings

---

CHANGELOG.md
tests/integration/sugar/test_transaction.py
xrpl/transaction/ledger.py

In this PR I added the `binary`, `min_ledger` and `max_ledger` of the `tx` method as described in https://xrpl.org/tx.html#tx
I also added some tests in `tests/integration/sugar/test_transaction.py`.
It solves this issue: https://github.com/XRPLF/xrpl-py/issues/191
The `get_transaction_from_hash` method now accepts `binary`, `min_ledger` and `max_ledger` parameters.
I included three new tests:
1. We submit a simple payment and then retrieve this transaction with `get_transaction_from_hash` without using the new parameters.
2. We submit a simple payment and then retrieve this transaction with `get_transaction_from_hash` with `binary=true`. We make sure the response includes a `hash` field.
3. We submit a simple payment and then retrieve this transaction with `get_transaction_from_hash` …

Included binary, min_ledger and max_ledger for get_transaction_from_hash

---

CHANGELOG.md
tests/unit/models/test_base_model.py
xrpl/asyncio/clients/exceptions.py
xrpl/models/transactions/transaction.py

This PR fixes a bug in the `Memo` model, where it doesn't properly provide memos in the format that the XRPL expects them in. It also makes the exception messages a little better.
The XRPL expects memos to be in the following format:
```python
{
"Memo": {
"MemoType": "687474703a2f2f6578616d706c652e636f6d2f6d656d6f2f67656e65726963",
"MemoData": "72656e74"
}
}
```
The library had been providing them like this:
```python
{
"MemoType": "687474703a2f2f6578616d706c652e636f6d2f6d656d6f2f67656e65726963",
"MemoData": "72656e74"
}
```
Fixes #247
Added a unit test. CI passes.

Fixes `Memo` dictionary handling

---

tests/integration/reqs/test_submit_only.py
tests/unit/models/test_base_model.py
xrpl/models/transactions/transaction.py

This PR fixes a bug with path serializations and adds a test to ensure this doesn't crop up again. Also cleaned up some other tests.
On a Twitch stream on 6/9, @hammertoe and @mDuo13 ran into a bug with the serialization of paths. Some failing sample code: https://gist.github.com/mDuo13/35358346ebb3d4dd8b5ea3757f0ed7a6#file-test_instantiate-py
Added a test that previously failed.

Fix path serialization bug

---

tests/unit/core/binarycodec/test_main.py
xrpl/core/binarycodec/types/uint64.py

Allow for `UInt64.from_value()` to accept lower case hex w/ length 1-16.
This PR allows for parsing lower case hex strings w/ length 1-16. It does this w/ an `rjust`, which pads the string `value` w/ leading zeros until it is length 16. This allows for it to be encoded like normal. 
Also, the `HEX_REGEX` was adjusted to allow for lower case hex strings.
Added a test to verify that encoding would work on both hex-strings w/ lowercase letters and hex-strings w/ length <16.

fix: UInt64.from_value() accepts lower case hex

---

poetry.lock
pyproject.toml

This PR allows users of xrpl-py who aren't using Python 3.10 to continue to use websockets v9.0 instead of needing to upgrade to v10.0.
People shouldn't have to upgrade websockets if they don't need to just to use xrpl-py.
CI passes.

fix: make Python 3.10 support more general

---

xrpl/asyncio/account/main.py
xrpl/asyncio/account/transaction_history.py
xrpl/asyncio/ledger/main.py
xrpl/asyncio/transaction/ledger.py
xrpl/asyncio/transaction/main.py
xrpl/asyncio/transaction/reliable_submission.py
xrpl/models/response.py

In `Response`, the result type was initially either a `List` or a `Dict`. But it turns out that there aren't actually any `rippled` responses where the result type is a `List`. So this PR removes that as an option in the type, which eliminates a lot of casting.
This was discovered while working on the Sidechain Launch Kit.
CI passes.

fix: make `response.result` type more specific

---

CHANGELOG.md
xrpl/account/main.py
xrpl/asyncio/account/main.py

This PR adds an optional parameter to the main account methods for the ledger index to query. It also sets the default ledger index for querying the sequence number to `"current"` instead of `"validated"`.
https://github.com/XRPLF/xrpl.js/pull/1719
CI passes. Tests pass.

feat: add optional `ledger_index` param to account methods

---

CHANGELOG.md
tests/integration/sugar/test_transaction.py
xrpl/asyncio/transaction/reliable_submission.py

This PR removes erroring in `send_reliable_submission` if the response code is something other than `tesSUCCESS`. It also adds an error if there is no `last_ledger_sequence` in the transaction.
Fixes #291. Also https://github.com/XRPLF/xrpl.js/pull/1704#pullrequestreview-773442168
Added a test for if the `last_ledger_sequence` is missing in a transaction.

fix: remove erroring in `send_reliable_submission` if not success

---

.github/workflows/unit_test.yml

This PR parallelizes linting and unit tests in the Github Actions CI. Previously, the CI required the linting and type-check tests to run before the unit tests would run. This meant that the tests would take longer to run, because they were running partially in series. This PR makes them run in parallel to save time, especially because the linting and type-checking takes the longest of all the tests.
make CI faster
CI passes.

chore: parallelize linting and unit tests in CI

---

CHANGELOG.md

This PR extends #294 and adds one more `py.typed` file that was missed in that previous PR.
I couldn't get the typing of `xrpl.constants` without it
CI passes. Tested the fix and it works.

fix: include missing `py.typed` file

---

xrpl/asyncio/clients/async_websocket_client.py
xrpl/asyncio/clients/websocket_base.py
xrpl/clients/websocket_client.py

fixes an issue encountered in integration tests for 3.7 and 3.8. also some minor refactoring of the websocket clients such that the sync client will now only check `self.is_open()` once when trying a network operator. previously it would have called it twice due to the implementation.

fixes typing issue with websockets in 3.7 and 3.8

---

CHANGELOG.md
tests/unit/core/binarycodec/types/test_currency.py
xrpl/core/binarycodec/types/currency.py

This PR fixes an issue where some tokens with non-traditional currency codes weren't being encoded properly; they were being incorrectly encoded as `XRP`. 
https://github.com/XRPLF/xrpl.js/pull/1857
Added a test that failed before the fix. CI passes.

fix: encoding issue with encoding non-traditional currency codes

---

CHANGELOG.md
tests/unit/core/binarycodec/test_main.py
xrpl/core/binarycodec/binary_wrappers/binary_serializer.py
xrpl/core/binarycodec/types/account_id.py
xrpl/core/binarycodec/types/hash.py
xrpl/core/binarycodec/types/serialized_dict.py

There's a bug in rippled that means that UNLModify pseudotransactions aren't being encoded properly (the account isn't being included in the encoded pseudo-tx). This PR adds a workaround for that issue.
https://github.com/XRPLF/xrpl.js/pull/1830
Added a test that failed before the fix. CI passes.

fix: add workaround for rippled UNLModify encoding bug

---

CHANGELOG.md
xrpl/models/__init__.py
xrpl/models/transactions/__init__.py

Title pretty much says it all.
I decided not to import the pseudotransactions at the `xrpl.models.transactions` level because that felt confusing, since they're not actually transactions.
Dogfooding showed that it was really annoying to have to specifically import `Transaction` from `xrpl.models.transactions.transaction`.
CI passes.

fix: export `Transaction`, `Response`, pseudotransactions at the `models` level

---

CHANGELOG.md
xrpl/models/amounts/issued_currency_amount.py
xrpl/models/currencies/issued_currency.py
xrpl/models/currencies/xrp.py

This PR allows users to use `int`s and `float`s for issued currencies and XRP amounts.
Follow-up to #319 
CI passes.

feat: add int/float support to `IssuedCurrency`, `XRP, `IssuedCurrencyAmount`

---

CHANGELOG.md
tests/integration/sugar/test_transaction.py
xrpl/asyncio/transaction/main.py

This PR pulls the fee for an AccountDelete transaction from the ledger, instead of using a hardcoded value.
A few months ago, the network voted to move the fee structure from 20/5 to 10/2. The fee for an autofilled AccountDelete transaction in xrpl-py wouldn't change, in that case, because it was hardcoded to 5 XRP. 
CI passes.

fix: use the ledger to determine the AccountDelete fee instead of hardcoding

---

CHANGELOG.md
tests/integration/sugar/test_ledger.py
xrpl/asyncio/ledger/main.py
xrpl/ledger/main.py

This PR refactors `get_fee` to incorporate the ledger load, so that the fee it returns scales appropriately when the ledger is under load, instead of always returning the minimum fee.
A minimum 10-drop fee currently does not work on mainnet. This PR uses the [formula used in xrpl.js](https://github.com/XRPLF/xrpl.js/blob/main/packages/xrpl/src/sugar/getFeeXrp.ts) to scale the fee based on ledger load.
CI passes. I tested by hand and confirmed that the fees are in the 5k drop range on mainnet right now.

feat: scales fee based on ledger load

---

CHANGELOG.md
xrpl/constants.py
xrpl/core/binarycodec/types/amount.py
xrpl/utils/xrp_conversions.py

This PR replaces all instances of Decimal's `setcontext` with the `localcontext` context manager.
Tests were failing for some weird dependency reason, so this PR also updates some dev dependencies as well.
It's better practice to use a context manager than to set global state. Plus, it's less likely to cause problems.
CI passes (tests don't pass if the context is set incorrectly).

fix: replace Decimal `setcontext` with `localcontext` context manager

---

CHANGELOG.md
tests/integration/sugar/test_transaction.py
xrpl/asyncio/transaction/__init__.py
xrpl/asyncio/transaction/main.py
xrpl/transaction/__init__.py
xrpl/transaction/main.py

This PR makes `_autofill_transaction` into a public method `autofill`. This exposes it to library users.
Tests were failing for some weird dependency reason, so this PR also updates some dev dependencies as well.
Requested by @mDuo13 because there is only a sign-and-autofill public method, not just an autofill method.
CI passes. Adjusted a few tests to call `autofill_transaction` directly instead of sign-and-autofill.

feat: make `autofill` a public method

---

CHANGELOG.md
xrpl/asyncio/clients/__init__.py

This PR exports `request_to_websocket` and `websocket_to_response` in the `xrpl.asyncio.clients` package. They were supposed to be exported, but it wasn't done properly.
Something random I noticed
CI passes.

fix: fix xrpl.asyncio.client exports

---

.github/workflows/unit_test.yml
.pre-commit-config.yaml
CHANGELOG.md
tests/unit/utils/test_sidechain.py
tests/unit/utils/test_time_conversions.py
tests/unit/utils/test_xrp_conversions.py
xrpl/models/requests/federator_info.py
xrpl/models/requests/request.py
xrpl/utils/__init__.py
xrpl/utils/sidechain.py

This PR:
* Adds `federator_info` request and response objects
* Adds a sugar util method to create a cross-chain payment transaction from a normal payment transaction
xrpl-py sidechain support
Added tests. CI passes.

feat: add sidechain-specific RPCs/sugar

---

CHANGELOG.md
xrpl/models/transactions/nftoken_burn.py

Add missing Owner field to the NFTokenBurn transaction.
Found thanks to this issue: https://github.com/XRPLF/xrpl.js/issues/1947
None

Add missing owner field to NFTokenBurn

---

CHANGELOG.md
tests/unit/models/currencies/test_issued_currency.py
xrpl/constants.py

According to [the xrpl.org page on currency codes](https://xrpl.org/currency-formats.html#standard-currency-codes), we should support lower-case currency codes.
Issue in the launch kit where lower-case currency codes were throwing an error.
Relevant test was fixed.

fix: allow lower-case currency codes

---

.github/pull_request_template.md

We always ignore the Before/After section anyways, since there is no UI component to this repo.
This section will soon not exist
N/A

chore: remove before/after from PR template

---

CHANGELOG.md
tests/unit/utils/test_parse_nftoken_id.py
xrpl/utils/parse_nftoken_id.py

Add a utility method to parse NFTokenIDs into a readable format.
In response to #1897 
Added unit tests for this new feature.

Add util to parse an NFTokenID

---

CHANGELOG.md
xrpl/models/requests/generic_request.py

Fix GenericRequest typing issue. 
Came up as part of sidechain dev.
According to [this StackOverflow post](https://stackoverflow.com/questions/36901/what-does-double-star-asterisk-and-star-asterisk-do-for-parameters), `**kwargs` should be typed according to an individual element that gets passed in to kwargs, instead of the overall collection of parameters. In this case, that means `Dict[str, Any]` becomes `Any`. 
CI passes

Fix GenericRequest mypy typing error

---

CHANGELOG.md
tests/unit/clients/test_json_rpc_client.py
xrpl/asyncio/clients/json_rpc_base.py

Add better error handling for invalid client URLs.
If you put in the wrong URL of a node for a client, the error that it returns is super opaque (it's a `JSONDecodeError`). We should return a better error/error message, so that it's clear that the user entered the wrong URL for the node.
This change now raises an `XRPLRequestFailureException` if the response can't be JSON decoded (`JSONDecodeError`).
https://github.com/XRPLF/xrpl-py/issues/353
Added unit tests.

add better error handling for invalid client URLs

---

CHANGELOG.md
tests/unit/models/requests/test_requests.py
xrpl/models/requests/generic_request.py

Fix bug in `GenericRequest.to_dict()`
There's an initialization bug in GenericRequest where `command` param doesn't get set to `method`:
```
>>> GenericRequest(command='validator_list_sites').to_dict()
{'method': 'zzgeneric_request', 'command': 'validator_list_sites'}
```
Correct state:
```
>>> GenericRequest(command='validator_list_sites').to_dict()
{'method': 'validator_list_sites'}
```
Added unit test to check GenericRequest state after initialization.

fix bug in GenericRequest.to_dict()

---

tests/unit/core/binarycodec/fixtures/data/data-driven-tests.json
tests/unit/core/binarycodec/types/test_serialized_dict.py
tests/unit/core/binarycodec/types/test_serialized_list.py
xrpl/core/binarycodec/definitions/field_instance.py
xrpl/core/binarycodec/main.py
xrpl/core/binarycodec/types/__init__.py
xrpl/core/binarycodec/types/serialized_list.py
xrpl/core/binarycodec/types/serialized_type.py
xrpl/core/binarycodec/types/st_array.py
xrpl/core/binarycodec/types/st_object.py

This PR:
* Fixes a typing issue with the binary parser that was caused by a circular dependency (which we now know how to resolve)
* Renames `SerializedDict` -> `STObject` and `SerializedList` -> `STArray` (to match rippled names)
* Refactors the list of types in `FieldInstance` to pull directly from `xrpl.core.binarycodec.types`, so that doesn't need to be edited every time a new type is added
There are no feature changes here; this is just an internal refactor.
I was adding some new types to the binary codec and thought that needing to add them in 2 places was unnecessary. I fixed a few other things to make the binary codecs more analogous as well.
CI passes. Tests that test the internal objects were edited to use the new type names (the methods exposed externally have not changed at …

refactor: redo binary codec types to simplify

---

CHANGELOG.md
tests/unit/utils/txn_parser/test_get_final_balances.py
xrpl/utils/__init__.py
xrpl/utils/txn_parser/__init__.py
xrpl/utils/txn_parser/get_balance_changes.py
xrpl/utils/txn_parser/get_final_balances.py
xrpl/utils/txn_parser/utils/__init__.py
xrpl/utils/txn_parser/utils/balance_parser.py
xrpl/utils/txn_parser/utils/types.py

- Add  and export `get_final_balances`
- Add `_compute_final_balance`
- Export `NormalizedNode`
- Change `BalanceChange` to `ComputedBalance`
- Change `BalanceChanges` to `ComputedBalances`
- Generally renamed some terms (function names and args) that indicate to only deal with balance changes. Now indicating to deal with computed balances.
The https://github.com/XRPLF/xrpl-py/pull/342 PR was splitted. For each exported function (get_balance_changes (already merged #383), get_final_balances, get_previous_balances and get_order_book_changes) there will now be a separate PR to make it easier to review. This PR adds the functionality to parse the final balances from a transaction's metadata (get_final_balances).
I added tests that are testing the same transactions as `get_balance_changes`.

Add final balances parser

---

CHANGELOG.md
xrpl/asyncio/transaction/main.py
xrpl/models/base_model.py
xrpl/models/requests/request.py
xrpl/models/requests/sign.py
xrpl/models/requests/sign_and_submit.py
xrpl/models/requests/sign_for.py
xrpl/models/requests/submit.py
xrpl/models/requests/submit_multisigned.py
xrpl/models/transactions/signer_list_set.py
xrpl/models/transactions/transaction.py
xrpl/utils/sidechain.py

This PR uses `TypeVar` to make the typing of `from_dict` and other similar constructor class methods work as expected.
I was getting really annoyed by it - it required a lot of unnecessary `cast`s.
mypy passes.

fix: fix typing of `from_dict` and other classmethods

---

CHANGELOG.md
tests/unit/models/test_base_model.py
xrpl/models/requests/sign.py
xrpl/models/requests/sign_and_submit.py
xrpl/models/requests/sign_for.py

This PR replaces the use of `to_dict` with `to_xrpl` in the `Sign`, `SignFor`, and `SignAndSubmit` requests (the requests that make rippled do the signing of the transaction for you). This makes the requests and the transactions actually valid.
I ran into this issue when working on sidechain tooling.
CI passes. Works when I use it.

fix: properly encode transactions in signing requests

---

CONTRIBUTING.md
tests/unit/core/binarycodec/fixtures/data/data-driven-tests.json
xrpl/core/binarycodec/definitions/definitions.json

This PR uses [xrpl-codec-gen](https://github.com/RichardAH/xrpl-codec-gen) to generate the `definitions.json` file. This rearranges the file a bit. It also removes some legacy bits of code that aren't actually in the rippled source code. 
No change in functionality.
@RichardAH mentioned this repo to me.
Tests pass. A couple of the data-driven tests needed to be removed because they weren't actually in the source code.

refactor: use `xrpl-codec-gen` for `definitions.json`

---

CHANGELOG.md
tests/unit/core/addresscodec/test_codec.py
tests/unit/core/keypairs/test_main.py
xrpl/core/addresscodec/codec.py
xrpl/core/keypairs/main.py
xrpl/wallet/main.py

The library currently assumes that all `ed25519` seeds use the `sEd` prefix. However, this is not necessarily true - they can also just have the `s` prefix, like the `secp256k1` seeds.
This PR adds support for those `ed25519` seeds.
needed for sidechains work
CI passes. Added tests to test the new functionality.

feat: add support for ED25519 seeds that don't use the `sEd` prefix

---

xrpl/models/nested_model.py
xrpl/models/transactions/signer_list_set.py
xrpl/models/transactions/transaction.py

Some objects are of the form:
```
{
"Memo": {
...
}
}
```
xrpl-py abstracts this away and creates the outer dictionary for you. There are a few objects that do this (`Memo`, `Signer`, and `SignerList`). There is a lot of copy-pasted code between these 3 objects. This PR seeks to simplify that by creating a parent object that inherits from BaseModel that handles this extra code.
I have a draft PR that has a few more of these objects, and it avoids having copy-pasted code.
CI passes. No change in functionality.

refactor: create new abstract model for nested dict objects

---

CHANGELOG.md
tests/unit/models/transactions/test_transaction.py
xrpl/models/transactions/transaction.py

Added ticket_sequence field to common Transaction class fields
Based on issue "Add common field ticket_sequence to Transaction #413" 
Wrote out unit tests

feat: added ticket_sequence to Transaction class common fields

---

CHANGELOG.md
pyproject.toml

Update CHANGELOG and pyproject.toml to 1.7.0

---

xrpl/asyncio/transaction/reliable_submission.py

Changed reliable submission ledger close time from 4 to 1 to enhance transaction speed
An example of where that might actually make the function run faster in a normal operation: according to [livenet.xrpl.org](http://livenet.xrpl.org/) a normal ledger on mainnet closes every 4.068 seconds right now. If the relsub method checks after 4 seconds, it would have to wait another 4 seconds before checking again, and take 8 seconds to finish, even if the transaction was validated after 4.068 seconds. If we switch to checking every 1 second, then it would take 5 seconds to finish.
Ran CI tests

feat: Shorten ledger close time from 4 to 1

---

.vscode/settings.json
CHANGELOG.md
mypy.ini
xrpl/asyncio/transaction/main.py
xrpl/transaction/main.py

This PR makes the behavior of `check_fee` much more reasonable. It will object when a user types in a fee that is over 10 drops and is signing offline, which is really annoying.
Previously, if you had a fee that was greater than 10 drops for any normal transaction, the method would object (unless you turned off `check_fee`, and it's hard to remember that you can do that).  There have been many previous complaints about this, but I can't find them right now (they don't appear to be in the repo's issues). Users should be able to enter in a higher fee if they want.
Relevant issue (and the reason why this feature exists): https://github.com/XRPLF/xrpl-py/issues/213

fix: adjust `check_fee` logic to be more reasonable

---

CHANGELOG.md
README.md
tests/integration/sugar/test_transaction.py
tests/unit/models/transactions/test_better_transaction_flags.py
xrpl/asyncio/transaction/__init__.py
xrpl/asyncio/transaction/main.py
xrpl/transaction/__init__.py
xrpl/transaction/main.py

Added alias function for `safe_sign_transaction` called `sign`
`safe_sign_transaction` is too long and unnecessary -- potentially deprecate/remove in xrpl-py 2.0

refactor: Alias function for safe_sign_transaction called sign

---

.github/workflows/integration_test.yml
.github/workflows/unit_test.yml

This PR switches the Github Actions from running on `ubuntu-latest` (which recently switched to 22.04) to `ubuntu-20.04`, which fixes tests.
It also adds testing support for Python 3.11.
Ubuntu 22.04 upgraded OpenSSL to version 3.0, which deprecated ripemd160. Github will not add support to the runner, because they want to run only the default version.
https://github.com/openssl/openssl/issues/16994
https://github.com/actions/runner-images/issues/6676
CI now passes.

fix: fix Github Actions issues

---

.github/workflows/integration_test.yml
.github/workflows/unit_test.yml
CHANGELOG.md
README.md
tests/integration/sugar/test_transaction.py
tests/unit/models/transactions/test_better_transaction_flags.py
xrpl/asyncio/account/main.py
xrpl/asyncio/account/transaction_history.py
xrpl/asyncio/clients/async_client.py
xrpl/asyncio/clients/async_websocket_client.py
xrpl/asyncio/clients/client.py
xrpl/asyncio/clients/json_rpc_base.py
xrpl/asyncio/clients/websocket_base.py
xrpl/asyncio/ledger/main.py
xrpl/asyncio/transaction/__init__.py
xrpl/asyncio/transaction/ledger.py
xrpl/asyncio/transaction/main.py
xrpl/asyncio/transaction/reliable_submission.py
xrpl/clients/sync_client.py
xrpl/clients/websocket_client.py
xrpl/transaction/__init__.py
xrpl/transaction/main.py

Merge main

---

.vscode/settings.json
xrpl/models/transactions/metadata.py
xrpl/utils/txn_parser/utils/nodes.py
xrpl/utils/txn_parser/utils/types.py

This PR uses `NotRequired` (equivalent to TypeScript `?` in interfaces) to simplify the metadata `TypedDict` types, making the code both simpler and easier to read.
I wanted to try out a new feature that was added in Python 3.11 and backported to previous Python versions.
The `TypedDict` metadata types were messy because `NotRequired` wasn't supported previously. But it has since been added to `typing_extensions`.
CI passes.

refactor: simplify `TypedDict` types

---

.github/workflows/integration_test.yml
.github/workflows/unit_test.yml
poetry.lock
pyproject.toml
xrpl/core/keypairs/__init__.py
xrpl/core/keypairs/helpers.py

Used RIPEMD160 algorithm from PyCrypto rather than hashlib since hashlib uses OpenSSL
Apparently Ubuntu LTS 22.04 upgraded OpenSSL to version 3.0 which deprecated RIPEMD160. As a result, our tests fail since they require this algorithm. We have reverted tests back to Ubuntu 20.04 to make them work, but this doesn’t seem ideal.

fix: Used RIPEMD160 algorithm from PyCrypto rather than hashlib

---

tests/integration/sugar/test_wallet.py
tests/unit/asyn/wallet/test_wallet_generation.py
xrpl/asyncio/wallet/wallet_generation.py

The NFT Devnet was a temporary network, and now it's not necessary since those changes have been merged with mainnet.
The network was recently unstable and it is blocking other PRs, so removing tests for it now.
We should remove the automatic inferrence for NFT-Devnet from the client if / when the network is permanently taken down.

Remove nft-devnet from tests

---

CHANGELOG.md
xrpl/asyncio/transaction/reliable_submission.py

solving txnNotFound issue https://github.com/XRPLF/xrpl-py/issues/312 due to racing condition - similar solution to JS  https://github.com/XRPLF/xrpl.js/pull/1883
add a condition to check for exceptions - If the exception is  `txnNotFound`, rerun the function with sleeper activated to wait for mainnet queue to clear up. 
- [X ] Bug fix (non-breaking change which fixes an issue)
Integration and unit tests passed but haven't reproduced the spotty bug yet

add check for txnNotFound

---

poetry.lock
tests/unit/core/binarycodec/types/test_hash_types.py
xrpl/core/binarycodec/types/hash128.py

Allow users to unset Hash128 field (EmailHash) using AccountSet.

unset hash128 using AccountSet

---

CHANGELOG.md
tests/unit/models/transactions/test_better_transaction_flags.py
xrpl/models/flags.py
xrpl/models/transactions/account_set.py

Adding support for this amendment https://github.com/XRPLF/rippled/pull/4336
Title says it all
CI Passes

Add disallow_incoming flags

---

CHANGELOG.md
xrpl/asyncio/wallet/wallet_generation.py

The nft-devnet was decommissioned on January 31st 2023 ([Blog Post](https://xrpl.org/blog/2023/nft-devnet-decommission.html)).

feat: remove nft-devnet faucet

---

tests/unit/models/transactions/test_better_transaction_flags.py
xrpl/models/transactions/account_set.py

`asfDisallowIncomingNFTOffer` to `asfDisallowIncomingNFTokenOffer`
Related to XRPLF/rippled#4442

rename DisallowIncoming flag for NFTs

---

CHANGELOG.md
xrpl/asyncio/transaction/reliable_submission.py

This PR handles request errors better. 
`XRPLRequestFailureException` is only triggered in one place upstream of the `tx` request, and that's when there's a `JSONDecodeError` (which occurs with an HTTP error and will therefore never have a value of `txnNotFound`). However, the response could have type `error`, and in that case the `"error"` value would be `txnNotFound` if that response error occurs. Other response errors should error normally now, instead of failing silently and getting caught elsewhere (namely in the opaque `KeyError: 'LastLedgerSequence'` that will occur on one of the immediately-following lines).
A request failed in a semi-production environment and it was really difficult to debug.
This is a difficult edge case to write a testcase for, since it involves a `tx` error. …

fix: handle relsub errors better

---

.vscode/settings.json
CHANGELOG.md
tests/unit/wallet/test_wallet.py
xrpl/wallet/main.py

This PR adds a `self.algorithm` to the wallet, to store the algorithm used to encode its seed.
This is really useful for the xbridge-cli work.

feat: save algorithm as a part of the wallet

---

CHANGELOG.md
xrpl/asyncio/transaction/reliable_submission.py

Title says it all. It's often easier to debug when you have the error message.
Someone had trouble debugging because the code wasn't mentioned.
This is a pretty trivial change that I don't think needs to be tested.

fix: improve error message for `tem` errors in relsub

---

CHANGELOG.md
tests/integration/sugar/test_transaction.py
xrpl/asyncio/transaction/reliable_submission.py

Errors that are validated (for example `tec` codes) weren't caught by any of the exceptions. This PR fixes that.
It took me a while to uncover a bug that I had in my code - the error was a `tec` error, which meant that it was eventually validated and none of the other error paths caught it.
CI passes. Added a test.
Potentially adding an option to `submit` on whether or not to error if the transaction has a non-`tesSUCCESS` code.

fix: better error handling in reliable submission

---

CHANGELOG.md
tests/integration/it_utils.py
tests/integration/sugar/test_transaction.py
xrpl/asyncio/transaction/__init__.py
xrpl/asyncio/transaction/main.py
xrpl/transaction/__init__.py
xrpl/transaction/main.py

- Longer aliases for signing/submitting functions have been removed. Specifically
- `submit_transaction` is now `submit`
- `safe_sign_transaction` is now `sign`
- `safe_sign_and_submit_transaction` is now `sign_and_submit`
- `safe_sign_and_autofill_transaction` is now `sign_and_autofill`
xrpl-py started with the longer versions of these names. In 1.8 we added the shorter aliases. Now we can simplify the interface by just having one name for the functions since `safe` and `transaction` weren't adding much meaning to the functions.
CI Passes

Remove long aliases for signing/submitting functions

---

CHANGELOG.md
tests/integration/reqs/test_submit_multisigned.py
tests/integration/sugar/test_transaction.py
tests/unit/models/transactions/test_transaction.py
xrpl/asyncio/transaction/main.py
xrpl/asyncio/transaction/reliable_submission.py
xrpl/transaction/main.py

Sign is currently async, but doesn't need to be (and it's bad practice to do online operations during signing)
Signing should happen offline (otherwise it may give the impression that keys are being leaked) - so having an asynchronous sign function is odd. The only reason for it is a single edge-case sanity check, which can be moved elsewhere to achieve similar coverage without clouding the purpose of `sign`. 
CI Passes

Make `sign` synchronous

---

CHANGELOG.md
README.md
snippets/paths.py
tests/integration/it_utils.py
tests/integration/reqs/test_submit_only.py
tests/integration/sugar/test_transaction.py
xrpl/asyncio/transaction/main.py
xrpl/transaction/main.py

`submit_and_wait` changed the param order since `Wallet` is optional, so we want to make all similar functions follow the same order to reduce confusion/frustration.
In order to be internally consistent, all signing/submitting functions will follow the parameter order of `transaction`, `client`, `wallet`, and then other parameters. (This is because `wallet` is optional for `submit_and_wait` and so must come after `client`)
This affects `autofill_and_sign` and `sign_and_submit`. 
CI Passes

refactor: Make param order for signing/submitting consistent

---

tests/integration/sugar/test_network_id.py

There was an integration test that was in the unit test section. This PR moves that over.
The test was added in #520. I noticed that unit tests were suddenly taking much longer to run.
CI passes.

fix(test): move integration test out from unit tests

---

CHANGELOG.md
xrpl/models/requests/account_channels.py
xrpl/models/requests/account_currencies.py
xrpl/models/requests/account_info.py
xrpl/models/requests/account_lines.py
xrpl/models/requests/account_nfts.py
xrpl/models/requests/account_objects.py
xrpl/models/requests/account_offers.py
xrpl/models/requests/account_tx.py
xrpl/models/requests/book_offers.py
xrpl/models/requests/deposit_authorized.py
xrpl/models/requests/gateway_balances.py
xrpl/models/requests/ledger.py
xrpl/models/requests/ledger_data.py
xrpl/models/requests/ledger_entry.py
xrpl/models/requests/nft_buy_offers.py
xrpl/models/requests/nft_history.py
xrpl/models/requests/nft_info.py
xrpl/models/requests/nft_sell_offers.py
xrpl/models/requests/no_ripple_check.py
xrpl/models/requests/request.py
xrpl/models/requests/ripple_path_find.py
xrpl/models/requests/transaction_entry.py

- Add `ledger_hash` and `ledger_index` to `account_nfts`, `nft_buy_offers`, and `nft_sell_offers` requests.
- Create `LookupByLedgerRequest` to clean up `ledger_hash` and `ledger_index` which are optional on most request objects.
- Add `nft_page` to `ledger_entry` request.
Closes https://github.com/XRPLF/xrpl-py/issues/467
Test passed.

feat: Add missing `nft_page`, `ledger_index` and `ledger_hash` fields to requests

---

CHANGELOG.md
tests/unit/models/currencies/test_xrp.py
xrpl/models/currencies/xrp.py

This PR fixes a disconnect between the docs for the `XRP().to_amount` method and what the function actually did. The docs seemed to be expecting an XRP amount, but the code was expecting an amount in drops.
I think an amount in XRP makes more sense. This is technically a breaking change, but I think it's more of a bugfix.
Ran into this issue while working on sidechain tooling
CI passes.

[BREAKING] fix: XRP().to_amount now expects XRP instead of drops

---

.github/workflows/unit_test.yml

This PR ensures that mypy/linting is run on the `snippets` folder.
Ran into an error.
CI passes.

test: run linting on snippets

---

CHANGELOG.md
xrpl/wallet/main.py

Fix mypy complaining about `Wallet.classic_address` being a `Callable` when it is an aliased `str` property. (Open mypy issue: https://github.com/python/mypy/issues/6700)
Currently aliasing a property is not properly typed by mypy. As a workaround you can switch to using `address` instead of `classic_address`, but this should resolve the issue until the mypy issue is fixed.
CI passes

fix: Fix `classic_address` aliasing issue

---

tests/integration/sugar/test_account.py

* Fix invalid account address
* Add invalid account test
* Remove magic address in favor of Wallet.create()
* Add classic_address
Add Jackson's integration test fix to 1.x.

Fix invalid account address (#611)

---

xrpl/models/requests/ledger_closed.py

This PR removes unnecessary parameters (ledger_hash and ledger_index) from the `LedgerClosed` model. (actually, ledger_hash and ledger_index field is for Response, not Request)
During a recent code review, it was discovered that the `LedgerClosed` model contained parameters that were not required in actual API (https://xrpl.org/ledger_closed.html)
CI Passes

fix: remove unnecessary parameters from LedgerClosed request

---

.readthedocs.yaml
docs/source/snippets.rst

ReadTheDocs has some breaking changes that need to be updated before September 15th.
- Adds build > os (a new required field as of October 25th)
https://blog.readthedocs.com/use-build-os-config/
Also fixes a misnamed 
Builds locally and by inspection follows the new rules.

docs: Update ReadTheDocs (rtd) configuration

---

CONTRIBUTING.md
docs/conf.py

Since 2.2.0, the xrpl-py docs have been loading with a new theme. This brings it back to the previous ReadTheDocs theme.
It seems that the default theme changed without warning (as far as we saw):
Autogenerated theme code from before 2.2.0:
https://readthedocs.org/projects/xrpl-py/builds/21212455/
Autogenerated theme code from versions after/including 2.2.0:
https://readthedocs.org/projects/xrpl-py/builds/21889906/
In general you can check builds and autogenerated theming by going to this build page: https://readthedocs.org/projects/xrpl-py/builds/
1. Click an individual build 
2. Click the "cat docs/conf.py" 
3. Scroll down past the "auto-generated below here" comment
4. Look for where the theme is defined
Inspection and the docs build locally with the RTD theme ✅ 
~~The true efficacy …

docs: Update theme to ReadTheDocs always (fixes regression)

---

CHANGELOG.md
xrpl/models/transactions/amm_bid.py

BidMin & BidMax types should be `IssuedCurrencyAmount` since they only accept LPToken amounts.
Current test already uses `IssuedCurrencyAmount`

fix BidMin & BidMax types

---

xrpl/asyncio/transaction/main.py

Closes #595 
We decided to keep the code in since it is more defensive and should be correct regardless of the network state.
N/A

docs: Remove TODO around build_version since we want the defensive coding

---

tests/integration/sugar/test_network_id.py
xrpl/asyncio/transaction/main.py

Tests are failing because the sidechain devnet no longer has a network ID greater than 1024.
The network ID tests now work.

fix: fix network ID tests + refactor network ID logic

---

CHANGELOG.md
snippets/bridge_transfer.py
tests/integration/sugar/test_network_id.py
tests/integration/sugar/test_wallet.py
xrpl/asyncio/wallet/wallet_generation.py

This PR removes support for sidechain-net1 (in the faucet code and snippets) and switches from a decommissioned bridge to a new bridge in the snippet.
The testing bridge was moved from sidechain-net1 to Devnet.
CI passes now.

chore: fix sidechain networks

---

.github/workflows/unit_test.yml

I ran into an issue where types were fine on the latest version but had issues on the oldest version.
CI passes.

ci: run type checking on earliest python version

---

tests/integration/reusable_values.py
tests/integration/transactions/test_escrow_create.py
tests/integration/transactions/test_ticket_create.py
tests/integration/transactions/test_xchain_account_create_commit.py
tests/integration/transactions/test_xchain_add_account_create_attestation.py
tests/integration/transactions/test_xchain_add_claim_attestation.py
tests/integration/transactions/test_xchain_claim.py
tests/integration/transactions/test_xchain_commit.py
tests/integration/transactions/test_xchain_create_bridge.py
tests/integration/transactions/test_xchain_create_claim_id.py
tests/integration/transactions/test_xchain_modify_bridge.py

Integration tests for #417. These tests are in a separate PR to make it easier to review and because tests won't pass in CI yet (since the amendment isn't a part of the Docker container yet), and will be merged into the feature branch prior to merging into `main`. Any bugfixes that were caught by these tests were moved to #417.
Passes locally when running a version of rippled with the amendment enabled.

test: add integration tests for sidechain transactions

---

.github/workflows/integration_test.yml
.github/workflows/snippet_test.yml
.github/workflows/unit_test.yml
docs/index.rst
xrpl/wallet/main.py

I was running something on Python 3.12 and wanted to make sure everything would work properly.
CI passes.

test: run tests on python 3.12

---

tests/unit/asyn/wallet/test_wallet.py
xrpl/asyncio/wallet/wallet_generation.py

This PR seeks to address https://github.com/XRPLF/xrpl-py/issues/364
This is an alternative approach competing with https://github.com/XRPLF/xrpl-py/pull/676
PR #676 needs to be closed after this PR is reviewed and merged.
This PR improves the handling of the faucet URL. I'm not sure if it needs to be included in the CHANGELOG. The changes are intuitive.
Some unit tests have been added to validate this change.
Many thanks to @justinr1234  for coming up with the design and code for this solution

Update faucet_url processing logic

---

CHANGELOG.md
tests/unit/asyn/wallet/test_main.py
xrpl/wallet/main.py

Fixes https://github.com/XRPLF/xrpl-py/issues/503
It's ideal to validate a seed before creating a `Wallet` object. This is helpful in generating readable error messages for the users.
Invalid seed input to `Wallet` will throw a different error. The current code throws a `ValueError`, this is hard to understand for users.
I have added a unit test that validates the Exception thrown upon empty seed inputs into the `Wallet` class constructor.

validate the contents of seed before creating a Wallet object

---

CHANGELOG.md
xrpl/models/transactions/amm_deposit.py

Sister PR from https://github.com/XRPLF/xrpl.js/pull/2667
Fixes https://github.com/XRPLF/xrpl.js/issues/2666
I don't know enough about this particular flag to write tests. Please let me know if you have ideas

add the missing AMMDeposit flag TF_TWO_ASSET_IF_EMPTY

---

CHANGELOG.md
tests/unit/models/requests/test_get_aggregate_price.py
xrpl/models/requests/get_aggregate_price.py

Use single Oracle class for Price Oracles support.
- Use single `Oracle` class for `get_aggregate_price` and `ledger_entry` to resolve duplicate name conflict.
Updated unit tests.

refactor: use single Oracle class for Price Oracles

---

tests/unit/models/transactions/test_oracle_set.py
xrpl/models/transactions/oracle_set.py

feat: add input check for OracleSet params AssetPrice and Scale

---

CHANGELOG.md
tests/unit/models/transactions/test_did_set.py
xrpl/models/transactions/did_set.py

Fix https://github.com/XRPLF/xrpl-py/issues/716
Fields within a DID object can only be deleted by setting an empty string. However, the regex in the `DIDSet` model do not account for empty strings.
Unit tests have been added to this effect

Empty strings in DIDSet transaction

---

CHANGELOG.md
tests/integration/reqs/test_feature.py
xrpl/models/requests/__init__.py
xrpl/models/requests/feature.py
xrpl/models/requests/request.py

This PR adds the `feature` RPC to the models.
There is now a non-admin user version of this RPC: https://github.com/XRPLF/rippled/pull/4781
Added integration tests.

feat: add `feature` RPC

---

CHANGELOG.md
xrpl/models/requests/ledger.py

Remove deprecated full parameter from ledger request model
In the [`ledger` API](https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/ledger-methods/ledger/), the `full` request parameter has been deprecated for quite awhile now.  As of Clio 2.2.0 with this particular commit https://github.com/XRPLF/clio/pull/1360, this API will return a request error if you provide that parameter.  This change removes this parameter from the ledger request model.  This change would not impact lib users as this using this parameter or setting it to true instead of default false previously would not have been used by rippled or Clio
Existing integration tests should continue to pass and manual testing of ledger API with xrpl-py against Clio 2.2.0 should succeed

Remove deprecated `full` parameter from ledger request model

---

CHANGELOG.md
xrpl/models/requests/ledger.py

Remove deprecated `accounts` and `type` parameters from ledger request model
In the [ledger API](https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/ledger-methods/ledger/), the accounts and type request parameters has been deprecated for quite awhile now. As of Clio 2.2.0 with this particular commit https://github.com/XRPLF/clio/pull/1360, this API will return a request error if you provide that parameter. This change removes this parameter from the ledger request model. This change would not impact lib users as this setting this parameter previously would not have been used by rippled or Clio
Existing integration tests should continue to pass and manual testing of ledger API with xrpl-py against Clio 2.2.0 should succeed

Remove deprecated `accounts` and `type` parameters from ledger request model

---

.github/workflows/integration_test.yml
.github/workflows/snippet_test.yml
.github/workflows/unit_test.yml
CHANGELOG.md
README.md
docs/index.rst
poetry.lock
pyproject.toml
tests/integration/transactions/test_payment.py
xrpl/models/base_model.py

Project can no longer build dependencies using Python 3.7. This PR removes Python 3.7 support to fix dependency installation and uses 3.8 as new default.

fix: remove Python 3.7 support to fix dependency installation and use 3.8 as new default

---

.github/workflows/integration_test.yml
.vscode/settings.json
CHANGELOG.md
tests/integration/it_utils.py
tests/integration/reqs/test_simulate.py
tests/integration/sugar/test_transaction.py
tests/unit/models/requests/test_simulate.py
tests/unit/models/test_base_model.py
xrpl/asyncio/transaction/__init__.py
xrpl/asyncio/transaction/main.py
xrpl/models/nested_model.py
xrpl/models/requests/__init__.py
xrpl/models/requests/request.py
xrpl/models/requests/sign.py
xrpl/models/requests/sign_and_submit.py
xrpl/models/requests/sign_for.py
xrpl/models/requests/simulate.py
xrpl/models/requests/submit_multisigned.py
xrpl/models/transactions/transaction.py
xrpl/transaction/__init__.py
xrpl/transaction/main.py

This PR adds support to xrpl-py for the new `simulate` RPC.
Spec: https://github.com/XRPLF/XRPL-Standards/tree/master/XLS-0069d-simulate
rippled PR: https://github.com/XRPLF/rippled/pull/5069
TODO

feat: add support for the `simulate` RPC (XLS-69d)

---

CHANGELOG.md
tests/integration/it_utils.py
tests/integration/transactions/test_amm_clawback.py
tests/unit/models/transactions/test_amm_clawback.py
xrpl/core/binarycodec/definitions/definitions.json
xrpl/models/transactions/__init__.py
xrpl/models/transactions/amm_clawback.py
xrpl/models/transactions/types/transaction_type.py

Documentation for the said amendment: https://xrpl.org/docs/references/protocol/transactions/types/ammclawback
C++ implementation PR: https://github.com/XRPLF/rippled/pull/5142/files
This PR implements the xrpl-py support for the said amendment.

Support AMMClawback amendment

---

.ci-config/rippled.cfg
CHANGELOG.md
tests/integration/it_utils.py
tests/integration/transactions/test_delete_oracle.py
tests/integration/transactions/test_offer_create.py
tests/integration/transactions/test_set_oracle.py
tests/integration/transactions/test_trust_set.py
tests/unit/models/transactions/test_better_transaction_flags.py
xrpl/models/transactions/trust_set.py

Add support for Deep freeze based off of proposed spec
https://github.com/XRPLF/XRPL-Standards/blob/dcb651403510237f26eeb854d550fa156d0e8b47/XLS-0077-deep-freeze/README.md
- Adds new setDeepFreeze flag
- Adds a new clearDeepFreeze flag

Deep freeze XLS-77d

---

CHANGELOG.md
tests/unit/core/binarycodec/types/test_issue.py
tests/unit/models/currencies/test_mpt_currency.py
xrpl/constants.py
xrpl/core/binarycodec/types/issue.py
xrpl/models/amounts/amount.py
xrpl/models/amounts/mpt_amount.py
xrpl/models/currencies/__init__.py
xrpl/models/currencies/currency.py
xrpl/models/currencies/mpt_currency.py
xrpl/models/transactions/clawback.py
xrpl/models/transactions/xchain_claim.py

This PR switches all `Issue` support to use a new type, `MPTCurrency`, instead of `MPTAmount` (since `Issue` doesn't have a `value` field). It also enhances some helper functions by changing them to be `TypeGuard`s.
This PR will need to make it into the next release to avoid breaking change issues.
#809 mistakenly added support for `MPTAmount` to `Issue`, when really it should be a new `MPTCurrency` type.
CI passes.
Update xrpl.js accordingly (https://github.com/XRPLF/xrpl.js/pull/2919)

fix: add `MPTCurrency` type instead of `MPTAmount` for `Issue`s

---

.github/workflows/snippet_test.yml
snippets/send_escrow.py
snippets/set_regular_key.py
snippets/submit_payment.py

This PR adds more time between snippet runs in the snippet CI tests to hopefully fix the flakiness of the tests. It also changes the destinations of several `Payment` transactions to be the faucet account instead of another faucet-generated wallets, thereby both reducing the number of times the faucet is called and simultaneously reducing the amount of funds the faucet wallet has to expend for a CI run.
Snippet tests were quite flaky, regularly failing.
CI passes more regularly.

ci: fix flakiness of snippet tests (hopefully)

---

CHANGELOG.md
tests/unit/models/test_base_model.py
tests/unit/models/transactions/test_payment.py
tests/unit/models/transactions/test_pseudo_transactions.py
xrpl/models/transactions/pseudo_transactions/enable_amendment.py
xrpl/models/transactions/pseudo_transactions/unl_modify.py
xrpl/models/transactions/transaction.py

By default flags field in transaction frozen class should be None rather than 0
When creating transactions using the frozen classes, the flags should not be 
Current tests 
No future tasks

Fix: default flags field for transaction frozen class should be None

---

.github/workflows/integration_test.yml
.github/workflows/snippet_test.yml
tests/integration/sugar/test_wallet.py
tests/integration/transactions/test_delegate_set.py
xrpl/asyncio/wallet/wallet_generation.py
xrpl/core/binarycodec/definitions/definitions.json

1. tecNO_DELEGATE_PERMISSION is returned instead of tecNO_PERMISSION when a transaction is executed by B on behalf of A without having A delegated permissions to B.
2. Add backoff retry logic to `test_wallet` IT that timeouts after 10 minutes to account errors due to new introduced rate limiting on testnet faucet.
3. Execute integration tests and snippets jobs one at a time.
4. Execute snippets only on merge to `main` branch.
To account for failing integration tests due to stricter rate limiting on testnet faucet.
Fixed the integration tests.

expect tecNO_DELEGATE_PERMISSION error code instead of tecNO_PERMISSION
